import { Turf, City, TimeSlot } from './types';

export const cities: City[] = [
  { id: 'mumbai', name: 'Mumbai', turfCount: 24, imageUrl: '/placeholder.svg' },
  { id: 'delhi', name: 'Delhi', turfCount: 18, imageUrl: '/placeholder.svg' },
  { id: 'bangalore', name: 'Bangalore', turfCount: 31, imageUrl: '/placeholder.svg' },
  { id: 'chennai', name: 'Chennai', turfCount: 15, imageUrl: '/placeholder.svg' },
  { id: 'hyderabad', name: 'Hyderabad', turfCount: 22, imageUrl: '/placeholder.svg' },
  { id: 'pune', name: 'Pune', turfCount: 19, imageUrl: '/placeholder.svg' },
];

export const turfs: Turf[] = [
  {
    id: 'turf-1',
    name: 'Green Arena Sports Complex',
    city: 'Mumbai',
    address: 'Andheri West, Mumbai',
    sports: ['football', 'cricket'],
    pricePerHour: 1500,
    rating: 4.8,
    reviewCount: 234,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Changing Rooms', 'Cafeteria', 'First Aid'],
    openTime: '06:00',
    closeTime: '23:00',
    featured: true,
    ownerId: 'owner-1',
    approvalStatus: 'approved',
    description: 'Premium multi-sport turf with world-class amenities. FIFA-standard playing surface with professional floodlights for night games.',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-2',
    name: 'Premier Turf Club',
    city: 'Mumbai',
    address: 'Powai, Mumbai',
    sports: ['football'],
    pricePerHour: 1800,
    rating: 4.9,
    reviewCount: 156,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Changing Rooms', 'Equipment Rental', 'Refreshments'],
    openTime: '05:00',
    closeTime: '22:00',
    featured: true,
    ownerId: 'owner-1',
    approvalStatus: 'approved',
    description: 'Top-rated football venue in Powai with premium artificial turf and professional coaching facilities.',
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-3',
    name: 'Cricket Pitch Pro',
    city: 'Delhi',
    address: 'Dwarka, Delhi',
    sports: ['cricket'],
    pricePerHour: 2000,
    rating: 4.7,
    reviewCount: 189,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Practice Nets', 'Coaching', 'Equipment Rental'],
    openTime: '06:00',
    closeTime: '21:00',
    featured: true,
    ownerId: 'owner-2',
    approvalStatus: 'approved',
    description: 'Professional cricket facility with multiple practice nets and experienced coaching staff.',
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-4',
    name: 'Sports Hub Bangalore',
    city: 'Bangalore',
    address: 'Koramangala, Bangalore',
    sports: ['football', 'cricket'],
    pricePerHour: 1600,
    rating: 4.6,
    reviewCount: 312,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Changing Rooms', 'Refreshments', 'WiFi'],
    openTime: '06:00',
    closeTime: '23:00',
    ownerId: 'owner-2',
    approvalStatus: 'approved',
    description: 'Popular multi-sport hub in Koramangala, perfect for weekend matches and corporate events.',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-5',
    name: 'Elite Football Arena',
    city: 'Bangalore',
    address: 'Indiranagar, Bangalore',
    sports: ['football'],
    pricePerHour: 2200,
    rating: 4.9,
    reviewCount: 445,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'VIP Lounge', 'Pro Equipment', 'Cafeteria', 'Shower'],
    openTime: '05:00',
    closeTime: '00:00',
    featured: true,
    ownerId: 'owner-3',
    approvalStatus: 'approved',
    description: 'Bangalore finest football arena with VIP lounge, premium facilities and tournament-grade playing surface.',
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-6',
    name: 'Chennai Cricket Ground',
    city: 'Chennai',
    address: 'Adyar, Chennai',
    sports: ['cricket'],
    pricePerHour: 1400,
    rating: 4.5,
    reviewCount: 178,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Practice Nets', 'Changing Rooms'],
    openTime: '06:00',
    closeTime: '22:00',
    ownerId: 'owner-3',
    approvalStatus: 'approved',
    description: 'Well-maintained cricket ground with practice nets and professional-grade pitch.',
    createdAt: '2024-04-15T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-7',
    name: 'Hyderabad Sports Village',
    city: 'Hyderabad',
    address: 'Gachibowli, Hyderabad',
    sports: ['football', 'cricket'],
    pricePerHour: 1700,
    rating: 4.7,
    reviewCount: 203,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Cafeteria', 'Equipment Rental', 'Changing Rooms', 'WiFi'],
    openTime: '06:00',
    closeTime: '23:00',
    featured: true,
    ownerId: 'owner-1',
    approvalStatus: 'approved',
    description: 'Sprawling sports complex in Gachibowli with multiple courts and world-class amenities.',
    createdAt: '2024-05-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-8',
    name: 'Pune Football Club',
    city: 'Pune',
    address: 'Kothrud, Pune',
    sports: ['football'],
    pricePerHour: 1300,
    rating: 4.4,
    reviewCount: 145,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Changing Rooms', 'Refreshments'],
    openTime: '06:00',
    closeTime: '22:00',
    ownerId: 'owner-2',
    approvalStatus: 'approved',
    description: 'Affordable football turf in Kothrud with quality playing surface.',
    createdAt: '2024-05-15T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'turf-9',
    name: 'Royal Cricket Academy',
    city: 'Mumbai',
    address: 'Bandra, Mumbai',
    sports: ['cricket'],
    pricePerHour: 2500,
    rating: 4.8,
    reviewCount: 89,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Practice Nets', 'Coaching', 'Pro Equipment', 'Cafeteria'],
    openTime: '05:00',
    closeTime: '23:00',
    featured: true,
    ownerId: 'owner-3',
    approvalStatus: 'approved',
    description: 'Premium cricket academy in Bandra with professional coaching and tournament-grade facilities.',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-15T00:00:00Z',
  },
  {
    id: 'turf-10',
    name: 'South Delhi Sports Arena',
    city: 'Delhi',
    address: 'Vasant Kunj, Delhi',
    sports: ['football', 'cricket'],
    pricePerHour: 1900,
    rating: 4.6,
    reviewCount: 267,
    imageUrl: '/placeholder.svg',
    amenities: ['Floodlights', 'Parking', 'Changing Rooms', 'Cafeteria', 'WiFi', 'First Aid'],
    openTime: '06:00',
    closeTime: '23:00',
    ownerId: 'owner-1',
    approvalStatus: 'approved',
    description: 'Modern sports arena in South Delhi with multi-sport capability.',
    createdAt: '2024-06-10T00:00:00Z',
    updatedAt: '2024-06-20T00:00:00Z',
  },
];

// Deterministic slot generation using date-based seed for stable UI
export const generateTimeSlots = (date: Date, pricePerHour: number): TimeSlot[] => {
  const slots: TimeSlot[] = [];
  const now = new Date();
  const isToday = date.toDateString() === now.toDateString();
  const dateStr = date.toISOString().split('T')[0];

  for (let hour = 6; hour <= 22; hour++) {
    const isPast = isToday && hour <= now.getHours();
    const seed = dateStr.split('-').reduce((a, b) => a + parseInt(b), 0) + hour;
    const isBooked = seed % 5 === 0 || seed % 7 === 0;

    slots.push({
      id: `slot-${hour}`,
      time: `${hour.toString().padStart(2, '0')}:00`,
      available: !isPast && !isBooked,
      price: pricePerHour,
    });
  }

  return slots;
};

export const calculateDiscount = (hours: number): number => {
  if (hours >= 4) return 0.20;
  if (hours >= 3) return 0.15;
  if (hours >= 2) return 0.10;
  return 0;
};
